CREATE DATABASE  IF NOT EXISTS `seventh_dguard`;

USE `seventh_dguard`;

DROP TABLE IF EXISTS `sdg_0002`;

CREATE TABLE `sdg_0002` (
  `ID` varchar(45) NOT NULL,
  `ID_SERVER` varchar(45) NOT NULL,
  `DESCRIPTION` varchar(150) NOT NULL,
  `SIZEINBYTES` int(11) NOT NULL,
  `DATE_ALTER` datetime NOT NULL,
  `DATE_INSERT` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABELA DE VIDEOS DE MONITORAMENTO'