CREATE DATABASE  IF NOT EXISTS `seventh_dguard`;

USE `seventh_dguard`;

DROP TABLE IF EXISTS `sdg_0003`;

CREATE TABLE `sdg_0003` (
  `ID` varchar(45) NOT NULL,
  `TYPE` varchar(45) NOT NULL,
  `FINISHED` int(11) NOT NULL,
  `DATE_INSERT` datetime NOT NULL,
  `DATE_ALTER` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABELA DE LOG RECICLAGEM DE VIDEOS'